//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFUIKitProfessional.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Astronaut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Astronaut()
        {
            this.AstronautFavorite = new HashSet<AstronautFavorite>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string status { get; set; }
        public string type { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public Nullable<System.DateTime> date_of_death { get; set; }
        public string nationality { get; set; }
        public string bio { get; set; }
        public string last_flight { get; set; }
        public string first_flight { get; set; }
        public int flights_count { get; set; }
        public byte[] profile_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AstronautFavorite> AstronautFavorite { get; set; }
    }
}
