//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFUIKitProfessional.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AstronautFavorite
    {
        public int id { get; set; }
        public int idClient { get; set; }
        public int idAstronaut { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Astronaut Astronaut { get; set; }
    }
}
