//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFUIKitProfessional.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutonTechEntities : DbContext
    {
        public AutonTechEntities()
            : base("name=AutonTechEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Astronaut> Astronaut { get; set; }
        public virtual DbSet<AstronautFavorite> AstronautFavorite { get; set; }
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventFavorite> EventFavorite { get; set; }
        public virtual DbSet<ImageDateFavorite> ImageDateFavorite { get; set; }
        public virtual DbSet<ImageGetter> ImageGetter { get; set; }
        public virtual DbSet<ImageRoadster> ImageRoadster { get; set; }
        public virtual DbSet<imageRocketsX> imageRocketsX { get; set; }
        public virtual DbSet<ImageShipsX> ImageShipsX { get; set; }
        public virtual DbSet<MarsRover> MarsRover { get; set; }
        public virtual DbSet<Roadster> Roadster { get; set; }
        public virtual DbSet<RoadsterFavorite> RoadsterFavorite { get; set; }
        public virtual DbSet<RocketsX> RocketsX { get; set; }
        public virtual DbSet<RocketsXFavorite> RocketsXFavorite { get; set; }
        public virtual DbSet<RoverFavorite> RoverFavorite { get; set; }
        public virtual DbSet<ShipsFavorite> ShipsFavorite { get; set; }
        public virtual DbSet<ShipsX> ShipsX { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
