//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFUIKitProfessional.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roadster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Roadster()
        {
            this.RoadsterFavorite = new HashSet<RoadsterFavorite>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime launch_date_utc { get; set; }
        public int launch_date_unix { get; set; }
        public int launch_mass_kg { get; set; }
        public string period_days { get; set; }
        public string mars_distance_km { get; set; }
        public Nullable<int> idImage { get; set; }
        public string details { get; set; }
    
        public virtual ImageRoadster ImageRoadster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoadsterFavorite> RoadsterFavorite { get; set; }
    }
}
