//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFUIKitProfessional.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipsX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShipsX()
        {
            this.ShipsFavorite = new HashSet<ShipsFavorite>();
        }
    
        public int id { get; set; }
        public string ship_name { get; set; }
        public string ship_model { get; set; }
        public string ship_type { get; set; }
        public string weight_kg { get; set; }
        public string year_built { get; set; }
        public Nullable<int> idImage { get; set; }
    
        public virtual ImageShipsX ImageShipsX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipsFavorite> ShipsFavorite { get; set; }
    }
}
